---

- name: Set up a local isolated vm for colte development
  hosts: ['colte1', 'colte2']
  vars:
    ansible_python_interpreter: /usr/bin/python3
  become: yes

  tasks:
    - name: Update and upgrade apt packages
      become: yes
      apt:
        upgrade: yes
        update_cache: yes

    - name: Install dependencies - software-properties-common
      apt:
        name: software-properties-common
        state: present

    - name: Add open5gs repo
      apt_repository:
        repo: ppa:open5gs/latest
    
    - name: Install open5gs
      apt:
        name: open5gs
        state: present
    
    - name: Copy network config
      copy:
        src: "../../configs/network/{{ inventory_hostname }}.yaml"
        dest: "/etc/netplan/60-static-routes.yaml"
        remote_src: no
      
    - name: Copy scripts
      copy:
        src: "../../scripts/"
        dest: "/home/vagrant/scripts"
        remote_src: no
        mode: u=rwx,g=rwx,o=rwx
    
    - name: Apply network changes
      command: netplan apply
      become: yes

    - name: Configure forwarding and rounting (script)
      command: /home/vagrant/scripts/configure-fwd
      become: yes

    - name: Configure open5gs ips
      command: /home/vagrant/scripts/open5gs-ip-config.py {{ colte_ip }}
      become: yes

    - name: Restart amf service
      systemd:
        name: open5gs-amfd
        state: restarted
        enabled: yes

    - name: Start smf service
      systemd:
        name: open5gs-smfd
        state: started
        enabled: yes

    - name: Start upf service
      systemd:
        name: open5gs-upfd
        state: started
        enabled: yes
